{% set name = "census" %}
{% set version = "0.8.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed7d092c72fad9f6f839e1501229490cb278403ae95529a02860f3012f02bc0a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - requests >=1.1.0
    - future

test:
  source_files:
    - census/tests
  imports:
    - census
    - census.tests
  commands:
    - pip check
    - pytest -v .
  requires:
    - pip
    - pytest

about:
  home: https://github.com/datamade/census
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A wrapper for the US Census Bureau's API
  description: |
    A simple wrapper for the United States Census Bureau's API.
    Provides access to ACS and SF1 data sets.
  dev_url: https://github.com/datamade/census
  doc_url: https://github.com/datamade/census/blob/master/README.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
