travis:
  secure:
    BINSTAR_TOKEN: U360/CGRWzfK6IOVnoxWfSIJsaVQtWE2Ve4MCvK2ZvrH/wOi1GMcR4wQdept2b1Pz3oLWyz/CT0qkIS5bghPRDB/IXFssbepW7Xqeb/QK/vqJzA6x4pzJwrcApWcWcFKv1Fo3NXUQ85TiBNRPxgqJLjAPmF2wuoZXWUKrhfJn/Da6a9xSmtrov5HGF5ik1k29qlW8xjj5iYxugk10AFyIkJ1RTmvK9u1q/fHV001qWKJ73ik8VDwqVrGUHvfRF8v88WhPDs4uHUnD9wZBlhaROjR1WJHw4O2a/zHD9coZduJgFOqdi4CCpdLV/3+h3bAPisfQrCeJvfw03N+vyVjwhXmE+9G8R/AVlkBezK1BE3G8UclZEc2QUo/pQ1EMUwJsYRNtyKk0B2o2z1cC8QnZuer7h40Ho3QKwWq83uQfQ3zN/X8xQiqR3Ih+8kJEvWDfLdJZ1UrGfRa+IygRTJvM5lsQJkR/X8JtFhGWSmgaN4eDGFuL03LoL91dB7M9oUWSCtB0JZINXpLykZgvOtOfLEjtCU/N39mhXiAGvh2CqV0uPNtlP95tKkBLaQYpQ4LSXyLIDzjhcihB+bssdlMMBvaZ+m6EJDwsuCzyncPt3sgCet3sBDti/gjIKqcVV0jmHG0qJN6Y2WCtIvgTF1fexT7W/MxFumUq1chMuetqbE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
