travis:
  secure:
    BINSTAR_TOKEN: frnJus7HewBBwTRIU+8RKmUD6Ug3jmAunxp3ok88FXDERLh8y7IoESU6h8AAWeza8SBwRPVJsBFZb6JgY0WQ8lDu1ltVHA5MDdV4OtBmWjt0xiTo9h0CWJxW1zfCJ6CbLbKpGpUboH5JyIFjTmSAdD9dEk7nUbgeRgTQv+MVjD3FOmqjAmPMA6ddfDRIugTdJYobNf5sP/8csuhNBBcR61XrK6aFjz7BSkewIL5xaK+ESFaqPJ9hhPeLHTjIAt6l7wBYzCGKiigBeH9wSDZSkmToCEHj5ItyXrgDFAm928B971cY57hRJcJM7zgRbql4C3jBCEb3gCfzDX8+PMUL386+hG4mfCtqic8PgVpzhGLfzU6NfHDPUwDy8OgulvqfGAzg2iqjfXb0xFJ59CZHQI1FmcuW4UgLtZZGcIclGnR5IlcFmA+gcLPH4ymzKHwz08Ay7RJVkA+vcLX46cAGsThKbX1n6ReqTMxe0999V2ZypwZ8b0fZnmc4ggMSNI10aeLp9MKP7W0Xfcpl1WdXkpVA6aGJbNZ+AYMEHg4g7RIRsGr6IshsVM5YUn/lu5KA4kGFc4bzQpmfG+1lfPds2dTPcXwbhGp4AReLZikJfbo0vcLISAcFSo5UWkIRSAP7wPlmu5bzlIkQC+ckIlwIdC7+KVJyg9zX961v5RCnC0w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
